/*
 * Copyright (c) 2025 Chen Xingyu <hi@xingrz.me>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_MFD_M5STACK_UNIT_EXTIO2_H_
#define ZEPHYR_INCLUDE_DRIVERS_MFD_M5STACK_UNIT_EXTIO2_H_

#define EXTIO2_REG_MODE_SETTING        0x00
#define EXTIO2_REG_OUTPUT_CTRL         0x10
#define EXTIO2_REG_DIGITAL_INPUT       0x20
#define EXTIO2_REG_ANALOG_INPUT_8B     0x30
#define EXTIO2_REG_ANALOG_INPUT_12B    0x40
#define EXTIO2_REG_SERVO_ANGLE_8B      0x50
#define EXTIO2_REG_SERVO_PULSE_16B     0x60
#define EXTIO2_REG_RGB_24B             0x70
#define EXTIO2_REG_PWM_DUTY_CYCLE      0x90
#define EXTIO2_REG_PWM_FREQUENCY       0xA0
#define EXTIO2_REG_FIRMWARE_VERSION    0xFE
#define EXTIO2_REG_I2C_ADDRESS_SETTING 0xFF

#define EXTIO2_MODE_INPUT    0
#define EXTIO2_MODE_OUTPUT   1
#define EXTIO2_MODE_ADC      2
#define EXTIO2_MODE_SERVO    3
#define EXTIO2_MODE_NEOPIXEL 4
#define EXTIO2_MODE_PWM      5

#endif /* ZEPHYR_INCLUDE_DRIVERS_MFD_M5STACK_UNIT_EXTIO2_H_ */
