/*
 * Copyright (c) 2025 Chen Xingyu <hi@xingrz.me>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_MFD_M5STACK_UNIT_BYTEBUTTON_H_
#define ZEPHYR_INCLUDE_DRIVERS_MFD_M5STACK_UNIT_BYTEBUTTON_H_

#define BYTEBUTTON_REG_BUTTON_VALUE_BITS   0x00
#define BYTEBUTTON_REG_BUTTON_VALUE_BYTES  0x60
#define BYTEBUTTON_REG_LED_BRIGHTNESS      0x10
#define BYTEBUTTON_REG_LED_SHOW_MODE       0x19
#define BYTEBUTTON_REG_LED_SELF_RGB888     0x20
#define BYTEBUTTON_REG_LED_SELF_RGB233     0x50
#define BYTEBUTTON_REG_LED_SYS_RGB888_0    0x70
#define BYTEBUTTON_REG_LED_SYS_RGB888_1    0x80
#define BYTEBUTTON_REG_FLASH_WRITE_BACK    0xF0
#define BYTEBUTTON_REG_IRQ_SETUP           0xF1
#define BYTEBUTTON_REG_FIRMWARE_VERSION    0xFE
#define BYTEBUTTON_REG_I2C_ADDRESS_SETTING 0xFF

#endif /* ZEPHYR_INCLUDE_DRIVERS_MFD_M5STACK_UNIT_BYTEBUTTON_H_ */
